version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: movieflix-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movieflix
    ports:
      - "5432:5432"
    volumes:
      - movieflix_data:/var/lib/postgresql/data

volumes:
  movieflix_data:
